config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "admin/dashboard#index"
end

app/views/admin/public_activity_activities/get_latests.html.erb
<% @activities.each do |activity| %>
	<li class="<%= activity.id > current_admin_user.actvity_checked ? 'ibox-heading' : '' %>" data-activity="<%=activity.id%>">
		<div class="dropdown-messages-box">  
			<a href="<%=auto_url_for(activity.trackable)%>", class="pull-left">
				<%if activity.owner %>
					<%= image_tag(activity.owner.photo, class: "img-circle") %>
				<% else %>
					<i class=-"fa fa-user fa-3x"></i>
				<% end %>
			</a>
			<div style="min-height: 40px;">
				<span class="pull-right small">
					<%=time_diff(activity.created_at, Time.now) + " ago" %>
				</span>
				<% if activity.key.split(".").last == "create" %>
					бүртгэсэн
				<% elsif activity.key.split(".").last == "update" %>
					шинэчилсэн
				<% elsif activity.key.split(".").last == "destroy" %>
					устгасан
				<% end %>
				<strong><%= display_name activity.trackable %> </strong>
				<br/>
				<small class="text-muted">
					<%=activity.created_at %>
				</small>
			</div>
		</div>
	</li>
	<li class="divider"></li>
<% end %>
<li> 
	<div class="text-center link-block"> 
		<a href="<%=admin_public_activity_activities_path%>"> 
			<strong>All Activity</strong>
			<i class="fa fa-angle-right"></i>
		</a>
	</div>
</li>